import type { SourceItem } from "../types";
import type { SourceAdapter } from "./types";

export const FIXTURE_ITEMS: SourceItem[] = [
  // Linear Issues
  {
    id: "linear-1",
    source: "linear",
    kind: "issue",
    title: "ENG-233 Session drops on page refresh in production",
    url: "https://linear.app/muster/issue/ENG-233",
    state: "in_progress",
    author: "sarah_k",
    updatedAt: "2026-08-29T14:20:00Z",
    ageDays: 1,
    labels: ["bug", "auth", "p0"],
    meta: { priority: "High", team: "Engineering" },
  },
  {
    id: "linear-2",
    source: "linear",
    kind: "issue",
    title: "ENG-241 Slow query on /api/v1/workspace/analytics",
    url: "https://linear.app/muster/issue/ENG-241",
    state: "todo",
    author: "devon_m",
    updatedAt: "2026-08-28T09:15:00Z",
    ageDays: 2,
    labels: ["performance", "backend"],
    meta: { priority: "Medium", team: "Backend" },
  },
  {
    id: "linear-3",
    source: "linear",
    kind: "issue",
    title: "ENG-219 Add OAuth scope validation for Slack integration",
    url: "https://linear.app/muster/issue/ENG-219",
    state: "in_progress",
    author: "alex_r",
    updatedAt: "2026-08-27T16:45:00Z",
    ageDays: 3,
    labels: ["security", "mcp"],
    meta: { priority: "High", team: "Security" },
  },
  {
    id: "linear-4",
    source: "linear",
    kind: "issue",
    title: "ENG-205 Dark mode color tokens contrast ratio audit",
    url: "https://linear.app/muster/issue/ENG-205",
    state: "done",
    author: "elena_v",
    updatedAt: "2026-08-26T11:00:00Z",
    ageDays: 4,
    labels: ["ui", "a11y"],
    meta: { priority: "Low", team: "Design" },
  },

  // Notion Pages
  {
    id: "notion-1",
    source: "notion",
    kind: "page",
    title: "Q3 2026 Architecture & MCP Roadmap",
    url: "https://notion.so/muster/q3-architecture-roadmap",
    state: "draft",
    author: "alex_r",
    updatedAt: "2026-08-29T10:00:00Z",
    ageDays: 1,
    labels: ["architecture", "roadmap"],
  },
  {
    id: "notion-2",
    source: "notion",
    kind: "page",
    title: "Incident Post-Mortem: Auth Gateway Latency Spike (Aug 24)",
    url: "https://notion.so/muster/post-mortem-aug-24",
    state: "review",
    author: "devon_m",
    updatedAt: "2026-08-28T18:30:00Z",
    ageDays: 2,
    labels: ["ops", "post-mortem"],
  },
  {
    id: "notion-3",
    source: "notion",
    kind: "page",
    title: "Customer Onboarding Specs & API Webhooks",
    url: "https://notion.so/muster/onboarding-spec",
    state: "published",
    author: "sarah_k",
    updatedAt: "2026-08-25T14:10:00Z",
    ageDays: 5,
    labels: ["docs", "api"],
  },

  // Gmail / Email
  {
    id: "gmail-1",
    source: "gmail",
    kind: "email",
    title: "Security Alert: New API Key scope requested for Github Sync",
    url: "https://mail.google.com/mail/u/0/#inbox/18a2bc4910f",
    state: "unread",
    author: "security-bot@muster.dev",
    updatedAt: "2026-08-30T07:12:00Z",
    ageDays: 0,
    labels: ["security", "urgent"],
  },
  {
    id: "gmail-2",
    source: "gmail",
    kind: "email",
    title: "Vercel Deployment Alert: Build sprint demo app staging",
    url: "https://mail.google.com/mail/u/0/#inbox/18a2b8e3902",
    state: "read",
    author: "notifications@vercel.com",
    updatedAt: "2026-08-29T22:05:00Z",
    ageDays: 1,
    labels: ["ci", "vercel"],
  },
  {
    id: "gmail-3",
    source: "gmail",
    kind: "email",
    title: "Re: Enterprise MCP server deployment timeline",
    url: "https://mail.google.com/mail/u/0/#inbox/18a29f8c122",
    state: "unread",
    author: "cto@partner.io",
    updatedAt: "2026-08-29T15:40:00Z",
    ageDays: 1,
    labels: ["partners", "high-priority"],
  },

  // Calendar Events
  {
    id: "cal-1",
    source: "calendar",
    kind: "event",
    title: "Sprint Review & Demo: BuildSprint 2026",
    state: "upcoming",
    author: "team@muster.dev",
    updatedAt: "2026-08-30T18:00:00Z",
    ageDays: 0,
    meta: { time: "18:00 IST", attendees: 4 },
  },
  {
    id: "cal-2",
    source: "calendar",
    kind: "event",
    title: "Architecture Sync: Zero-Knowledge Proof & Soroban",
    state: "upcoming",
    author: "alex_r",
    updatedAt: "2026-08-30T14:30:00Z",
    ageDays: 0,
    meta: { time: "14:30 IST", attendees: 3 },
  },
  {
    id: "cal-3",
    source: "calendar",
    kind: "event",
    title: "Customer Feedback: Generative Dashboard Usability",
    state: "completed",
    author: "sarah_k",
    updatedAt: "2026-08-29T11:00:00Z",
    ageDays: 1,
    meta: { time: "11:00 IST", attendees: 5 },
  },
];

/* GitHub demo data, used when no token is configured. Deliberately shares people
   and project names with the other fixtures so a cross source panel looks
   genuinely correlated rather than like five unrelated lists. */
export const GITHUB_FIXTURES: SourceItem[] = [
  {
    id: "github-pr-482",
    source: "github",
    kind: "pr",
    title: "#482 fix(auth): resolve race condition in token refresh loop",
    url: "https://github.com/muster-org/muster/pull/482",
    state: "open",
    author: "alex_r",
    updatedAt: "2026-08-19T14:30:00Z",
    ageDays: 11,
    labels: ["bug", "auth", "p0"],
    meta: { repo: "muster-org/muster", ci: "failed", review: "requested" },
  },
  {
    id: "github-pr-475",
    source: "github",
    kind: "pr",
    title: "#475 perf(db): index workspace_id on mcp_logs",
    url: "https://github.com/muster-org/muster/pull/475",
    state: "open",
    author: "devon_m",
    updatedAt: "2026-08-26T19:00:00Z",
    ageDays: 4,
    labels: ["performance", "sql"],
    meta: { repo: "muster-org/muster", ci: "passed", review: "none" },
  },
  {
    id: "github-pr-491",
    source: "github",
    kind: "pr",
    title: "#491 chore(deps): bump @provablehq/sdk from 0.8.1 to 0.9.0",
    url: "https://github.com/muster-org/muster/pull/491",
    state: "open",
    author: "dependabot",
    updatedAt: "2026-08-29T08:15:00Z",
    ageDays: 1,
    labels: ["dependencies"],
    meta: { repo: "muster-org/muster", ci: "passed", review: "none" },
  },
  {
    id: "github-pr-488",
    source: "github",
    kind: "pr",
    title: "#488 feat(mcp): multi-server panel layout composition",
    url: "https://github.com/muster-org/muster/pull/488",
    state: "open",
    author: "mintu",
    updatedAt: "2026-08-30T04:20:00Z",
    ageDays: 0,
    labels: ["feature", "core"],
    meta: { repo: "muster-org/muster", ci: "running", review: "requested" },
  },
  {
    id: "github-issue-467",
    source: "github",
    kind: "issue",
    title: "#467 Session drops when the OAuth scope changes mid-flight",
    url: "https://github.com/muster-org/muster/issues/467",
    state: "open",
    author: "sarah_k",
    updatedAt: "2026-08-22T11:05:00Z",
    ageDays: 8,
    labels: ["bug", "auth"],
    meta: { repo: "muster-org/muster", comments: 6 },
  },
];

export const linearAdapter: SourceAdapter = {
  id: "linear",
  label: "Linear",
  isLive: () => false,
  fetch: async (limit) =>
    FIXTURE_ITEMS.filter((i) => i.source === "linear").slice(0, limit),
};

export const notionAdapter: SourceAdapter = {
  id: "notion",
  label: "Notion",
  isLive: () => false,
  fetch: async (limit) =>
    FIXTURE_ITEMS.filter((i) => i.source === "notion").slice(0, limit),
};

export const gmailAdapter: SourceAdapter = {
  id: "gmail",
  label: "Gmail",
  isLive: () => false,
  fetch: async (limit) =>
    FIXTURE_ITEMS.filter((i) => i.source === "gmail").slice(0, limit),
};

export const calendarAdapter: SourceAdapter = {
  id: "calendar",
  label: "Calendar",
  isLive: () => false,
  fetch: async (limit) =>
    FIXTURE_ITEMS.filter((i) => i.source === "calendar").slice(0, limit),
};
