import type { IncomingMessage, ServerResponse } from "node:http";

/* The handler is imported lazily, inside the request, on purpose.

   A static import runs the whole server module graph at cold start, and
   anything that throws there fails the invocation before any of our code
   runs, which Vercel reports only as FUNCTION_INVOCATION_FAILED with no
   detail. Importing inside a try block means a load failure comes back as
   readable JSON instead. */
export const config = { runtime: "nodejs", maxDuration: 60 };

type VercelRequest = IncomingMessage & { body?: unknown };

async function readBody(req: VercelRequest): Promise<unknown> {
  if (req.body !== undefined && req.body !== null) {
    if (typeof req.body === "string") {
      try {
        return JSON.parse(req.body);
      } catch {
        return {};
      }
    }
    return req.body;
  }
  const chunks: Buffer[] = [];
  for await (const chunk of req) chunks.push(chunk as Buffer);
  if (chunks.length === 0) return {};
  try {
    return JSON.parse(Buffer.concat(chunks).toString());
  } catch {
    return {};
  }
}

function send(res: ServerResponse, status: number, body: unknown): void {
  res.statusCode = status;
  res.setHeader("Content-Type", "application/json");
  res.end(JSON.stringify(body));
}

export default async function route(req: VercelRequest, res: ServerResponse): Promise<void> {
  try {
    // One pre-bundled file, generated by scripts/build-server.mjs at build time.
    const { handle } = await import("./_server.js");

    const host = req.headers.host ?? "localhost";
    const proto = (req.headers["x-forwarded-proto"] as string | undefined) ?? "https";
    const url = new URL(req.url ?? "/", `${proto}://${host}`);

    const result = await handle({
      method: req.method ?? "GET",
      path: url.pathname,
      query: Object.fromEntries(url.searchParams),
      cookieHeader: req.headers.cookie,
      origin: url.origin,
      body: req.method === "POST" ? await readBody(req) : undefined,
    });

    if (result.cookies?.length) res.setHeader("Set-Cookie", result.cookies);

    if (result.redirect) {
      res.statusCode = result.status;
      res.setHeader("Location", result.redirect);
      res.end();
      return;
    }

    send(res, result.status, result.body);
  } catch (err) {
    /* 200 rather than 500: the client can render a fallback layout from any
       JSON body, but not from a Vercel error page, and the message is the only
       way to see what went wrong without dashboard access. */
    console.error("[muster] function failed:", err);
    send(res, 200, {
      error: err instanceof Error ? err.message : String(err),
      where: "api/[...route]",
      node: process.version,
      stack: err instanceof Error ? err.stack?.split("\n").slice(0, 6) : undefined,
    });
  }
}
